export enum LabMapper {
    RESOURCE_HYDROGEN = 0,
    RESOURCE_HYDROGEN2 = 1,
    RESOURCE_HYDROGEN3 = 2,
    RESOURCE_HYDROGEN4 = 3,
    RESOURCE_ZYNTHIUM = 4,
    RESOURCE_OXYGEN = 5,
    RESOURCE_KEANIUM = 6,
    RESOURCE_LEMERGIUM  = 7,
    RESOURCE_UTRIUM = 8,
    RESOURCE_HYDROGEN5 = 9,
  }
